spring:
  thymeleaf:
    cache: true
    check-template: true

    #.html 파일 불러올 경로 설정
    prefix: classpath:/templates/

    # 파일 확장자
    suffix: .html

    mode: HTML

    check-template-location: true
  servlet:
    multipart:
      enabled: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  main:
    allow-bean-definition-overriding: false

  mvc:
    # spring mvc 정적경로
    static-path-pattern: /static/**

  jpa:
    open-in-view: false

server:
  port: 8081